### PR TITLE
Update buildgraph-view.properties

### PR DESCRIPTION
**Pull request by pskumar448**

### CODE REVIEW

**Comment by bsideup** [comment]
Hey @pskumar448 

Please, mark your tag as release (you can do it in GitHub UI, go to "releases" page, select your latest release and click "publish release")

Currently there are 0 releases in your repository, only tags

**Comment by pskumar448** [comment]
Sergei,
I just did the 6th release for buildgraph-view plugin.

Thanks,
Suresh

**Comment by bsideup** [comment]
@pskumar448 

Yes, I see. However, according to GitHub's API, it's not a release (yet). To make it released, just go to https://github.com/jenkinsci/buildgraph-view/releases/tag/buildgraph-view-1.3 , press "edit tag" and then press "publish release".

Otherwise it's just a tag

**Comment by pskumar448** [comment]
Done. Published.

**Comment by bsideup** [comment]
@pskumar448 👍 ok, now I see it. Build is running right now, will accept once it's green :) 

Once this PR is accepted, there will be no need to send any PRs anymore - just create another release and Jucies will automatically publish it.

**Comment by pskumar448** [comment]
Yes I saw your mails in Jenkins dev mail list. And I did the same by
removing tag and version. Good job Sergei

**Comment by bsideup** [comment]
@pskumar448 :tada: released:
https://github.com/jucies/jucies.github.io/commit/41be42fa1d61a016f71073476b7d17d0b2f6375c

(As you can see, releases now trackable thanks to pretty-printed json)

**Pull request merged**
