### PR TITLE
Release buildgraph-view 1.2

### PR DESCRIPTION
**Pull request by pskumar448**

### CODE REVIEW

**Comment by bsideup** [comment]
@pskumar448 congratulations! Your plugin was added to Jucies :) 

You can verify it here:
http://jucies.github.io/update-center.json

**Comment by bsideup** [comment]
@pskumar448 

FYI I just pushed a new feature - support for optional "tag" property to make it possible to use nicer, semantic version:
See an example here: https://github.com/jucies/releases/blob/master/plugins/github-pullrequest.properties

In your case, you can change it to:

``` properties
repository = jenkinsci/buildgraph-view
tag = buildgraph-view-1.2
version = 1.2
```

**Comment by pskumar448** [comment]
@bsideup 
Can I submit a new PR for the updated one.

**Comment by bsideup** [comment]
Sure!

**Pull request merged**
