### PR TITLE
git-changelog, violation-comments-to-stash, violation-comments-to-github

### PR DESCRIPTION
**Pull request by tomasbjerre**

### CODE REVIEW

**Comment by bsideup** [comment]
Hey @tomasbjerre,

Please, create a release in each repository or use "tag/version" notation. Currently you're using "repository" only field, this is "GitHub release" mode and GitHub release is required :)

**Comment by tomasbjerre** [comment]
They all have releases, but I need to upload hpi-files right?
https://github.com/jenkinsci/violation-comments-to-github-plugin/releases
https://github.com/jenkinsci/violation-comments-to-stash-plugin/releases
https://github.com/jenkinsci/git-changelog-plugin/releases

**Comment by bsideup** [comment]
@tomasbjerre no, you don't have to upload anything. These, actually, are not releases - the weird thing with GitHub. The release has special notation when you convert a tag to it. 

I see it here:
https://github.com/jenkinsci/violation-comments-to-stash-plugin/releases

(it's not the latest tag, but at least there is a release)

Basically, you can do it with GitHub UI - just select the latest tag, press "Edit tag" and publish it as "Release"

**Comment by bsideup** [comment]
@tomasbjerre BTW, do you really want "-plugin" suffix for your plugins? Usually, it's dropped from ID from plugin. 

I.e. "git-changelog.properties" instead of "git-changelog-plugin.properties"

**Comment by tomasbjerre** [comment]
Ok, I changed that. Does the error mean I need to change versioning?

**Comment by bsideup** [comment]
@tomasbjerre ok, now I see the releases! Only one simple additional change is required - there is a limitation in Jenkins - it will not handle versions like "my-plugin-1.2", and since you use Maven plugin, default tag name will be "plugin-id-${version}". 

In Jucies, version equal to the id of release. But you can rename your release (just in GitHub's UI) to make it look like "1.2", or "1.2.3", or any other valid **semantic** version.

**Comment by bsideup** [comment]
Sorry to see you having all this issues, luckily, this is "one time" operation. I will attempt to find a workaround for tags like "plugin-id-1.2" to simplify your life in the near future!

**Comment by bsideup** [comment]
@tomasbjerre actually, I see an option how to do it quickly. Let me try (no actions from your side required)

**Comment by tomasbjerre** [comment]
No worries, I really think this is a great idea.

**Comment by tomasbjerre** [comment]
I changed the release names first, now I also created new tags with correct names.

**Comment by bsideup** [comment]
@tomasbjerre I see some build errors of violation-comments-to-stash-plugin: 

https://jitpack.io/com/github/jenkinsci/violation-comments-to-stash-plugin/1.14/build.log

Looks like you use Java 7, but language level is Java 6 :)

if so - consider changing this lines ( https://github.com/jenkinsci/violation-comments-to-stash-plugin/blob/master/pom.xml#L90 ) to 1.7

**Comment by bsideup** [comment]
@tomasbjerre Alternatively create a jitpack.yml file in the root of your repository and specify a jdk version:

``` yaml
jdk:
  - oraclejdk7
```

**Comment by bsideup** [comment]
FYI everything else looks fine, builds for other two plugins are green and ready to be merged. We can merge them and then merge stash plugin during the next iteration if you want :)

**Comment by bsideup** [comment]
@tomasbjerre congratulations! All three were released successfully! You can verify it here:
https://jucies.github.io/update-center.json

**Comment by bsideup** [comment]
Now, to release new version, just press "create a new release" on "Releases" page, so you can release your latest master (without doing mvn release:release, publishing, etc...)

**Pull request merged**
