### PR TITLE
Update buildgraph-view.properties

### PR DESCRIPTION
**Pull request by pskumar448**

### CODE REVIEW

**Comment by bsideup** [comment]
👍

**Comment by pskumar448** [comment]
@bsideup 
If we release a plugin like this, is this going to reflect in Jenkins Update Center, means official repo.

**Comment by bsideup** [comment]
@pskumar448 unfortunately, these two are completely different ways of releasing Jenkins plugins. You still can release your plugins to both JUC and Jucies btw, Jenkins will handle it properly.

I personally prefer Jucies because it's much faster and simpler (once PR is merged it takes 1-3 minutes (for Travis build) to make it available for **everyone**. In JUC it takes 1-3 days to propagate changes to all mirrors)

I have some plans to discuss with CloudBees about integrating Jucies more closely, hopefully it will became something more or less official, but not for now.

**Comment by bsideup** [comment]
@pskumar448 FYI plugin was released, here is a screenshot from our Jenkins (where Jucies plugin is installed):

https://gyazo.com/8fad67fa3e0c0e32ab29b6323199c25b

**Comment by bsideup** [comment]
Twitter post:
https://twitter.com/jucies4jenkins/status/723780861666181120

**Comment by pskumar448** [comment]
Ok. I felt it is easy to release plugin. 
Will hope CloudBees will agree to integrate this. Nice work.
BTW I am not able to see in my update center, where as I too have the installed plugin.

**Comment by bsideup** [comment]
Did you press "Check now" to update your plugin list?

**Comment by pskumar448** [comment]
Yes I did.

**Comment by bsideup** [comment]
@pskumar448 I think I know what is it. Did you install previous one, with `buildgraph-view-` prefix? I think Jenkins is treating it as newer (or the same since timestamps are identical) if so :)

**Comment by pskumar448** [comment]
Yes. is there a chance to delete the wrong one and rebuild the new one.

**Comment by bsideup** [comment]
Well, it's already "right one" in Jucies, but you can also create a new
release (basically, you can you it in GitHub UI, just go to releases page
and create a new one, i.e. "1.2.1"), then send a PR with updated version.

Actually, I think you're only one who has downloaded version with prefix,
so you can just ignore it :)

**Pull request merged**
